### PR TITLE
add yundai-wang's information on sole's repo

### PR DESCRIPTION
**Pull request by wydhhh**
this pr is for adding new member yundai-wang's info to sole's repo.

### CODE REVIEW

**Comment by wydhhh** [comment]
none

**Comment by wydhhh** [comment]
none

**Comment by wydhhh** [comment]
none

**Comment by GraysonLiu23** [comment]
请换一张小一点的照片，尽量控制在40KB以内

**Comment by wydhhh** [comment]
OK学长

**Pull request merged**
